name: nf-select CI
on:
  push:
    branches:
      - main
      - dev
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - main
      - dev
jobs:
  build:
    name: Build nf-select
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java_version: ["17"]

    steps:
      - name: Environment
        run: env | sort

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          submodules: true

      - name: Setup Java ${{ matrix.java_version }}
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java_version }}
          architecture: x64

      - name: Clean
        run: ./gradlew clean

      - name: Tests
        run: ./gradlew jsonPlugin
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=false"
